version: '3.8'
services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"
    volumes:
      - dynamodb_data:/data
    networks:
      - dynamodb_network
    # restart: always      # Automatically restart when Docker starts

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
    networks:
      - dynamodb_network
    depends_on:
      - dynamodb-local
    # restart: always      # Automatically restart when Docker starts

volumes:
  dynamodb_data:

networks:
  dynamodb_network:
