version: "3.8"
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566" # Gateway for all LocalStack services
    environment:
      - SERVICES=s3     # Enable S3 service
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=1         # Optional: Enable debug logs
    restart: always      # Automatically restart when Docker starts
