version: "3.8"
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"   # main edge port
      - "8080:8080"   # LocalStack Web UI
    environment:
      - SERVICES=s3,sqs,lambda  # add other services you need
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
